name: CI - Build, Test & Coverage

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ./src/**/*.csproj

      - name: Build all projects
        run: dotnet build ./src/**/*.csproj -c Release --no-restore

      - name: Run tests with code coverage
        run: dotnet test dotenv.net.sln /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=./coverage/

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ github.token }}
          path-to-lcov: ${{ github.workspace }}/tests/dotenv.net.Tests/coverage/coverage.info
